name: Deploy New Changes to Prod

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deployment to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.VPS_USERNAME }}/tmp
          git clone https://github.com/${{ github.repository }}.git ${{ github.event.repository.name }}
          rsync -a --exclude='.git' --exclude='Dockerfile' --exclude='docker-compose.yml' --exclude='transcript' --exclude='clips' --exclude='videos' --exclude='thumbnails' ${{ github.event.repository.name }}/ ${{ secrets.VPS_PROJECT_PATH }}
          cd ${{ secrets.VPS_PROJECT_PATH }}
          chmod -R 777 backend/transcript
          chmod -R 777 backend/clips
          chmod -R 777 backend/videos
          chmod -R 777 backend/thumbnails
          docker compose down
          docker compose up -d --build
          cd /home/${{ secrets.VPS_USERNAME }}/tmp
          rm -rf ${{ github.event.repository.name }}
